FROM python:3.12-bullseye

WORKDIR /usr/src/app

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
WORKDIR /usr/src/app/ilpostcast
ENV DB_FILE=../ilpostcast.db
CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0"]
