version: "3.4"

services:
    ilpostcastserver:
        container_name: ilpostcastserver
        build:
            context: .
            dockerfile: Dockerfile.server
            network: host
        volumes:
            - .:/usr/src/app
        ports:
            - "5000:5000"
        restart: unless-stopped
        networks:
            - raspberry-swag

networks:
    raspberry-swag:
        name: swag-reverseproxy_raspberry-swag
        external: true
